### ISSUE TITLE
[Jira] Deactivating a user not working

### ISSUE THREAD

**Issue by JoeMcMahon87** [atlassian-api/atlassian-python-api#161]
Using the API I make a call to jira.user_deactivate with the user name via an admin user and I get no errors, but when I log into the site, the user still has full site access. Is this method non-functional?

**Comment by gonchik** [comment]
Hi! 

On which version did you test it? 
in reality, I like to use the some rest endpoint. 

Cheers,
Gonchik Tsymzhitov

**Comment by JoeMcMahon87** [comment]
atlassian-python-api==1.11.19

I'd prefer the Python API - are you saying that I should change over to the Rest endpoint instead?

**Comment by jefft** [comment]
I can confirm, `user_deactivate()` doesn't work in 1.13.7. The POST isn't even being sent.

The problem is on [rest_client.py:107](https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/rest_client.py#L107-L108):

````
        if files is None:
            data = json.dumps(data)
````
I'm not sure what those lines are trying to achieve, but the effect is to convert `data` from a dict to a str. Then later, in [oauthlib/common.py](https://github.com/oauthlib/oauthlib/blob/master/oauthlib/common.py), we find that the body is assumed to be urlencoded, which ours isn't, and the code just returns None, so there's no decent errors, just a silent failure:

````
def extract_params(raw):
    """Extract parameters and return them as a list of 2-tuples.

    Will successfully extract parameters from urlencoded query strings,
    dicts, or lists of 2-tuples. Empty strings/dicts/lists will return an
    empty list of parameters. Any other input will result in a return
    value of None.
    """
    if isinstance(raw, bytes) or isinstance(raw, unicode_type):
        try:
            params = urldecode(raw)
        except ValueError:
            params = None
````

Commenting out those two lines fixes the immediate problem. The data is kept as a dict, not a str, and the relevant POST now gets sent.

Sadly even with this fix, `user_deactivate()` won't work, at least with oauth, because Jira [websudo](https://confluence.atlassian.com/adminjiraserver/configuring-secure-administrator-sessions-938847890.html) intercepts the request and demands an admin password. This can be seen by turning on debug logging (`import logging; logging.basicConfig(level=logging.DEBUG)`). I haven't had any luck manually calling `user_get_websudo()`. 

https://jira.atlassian.com/browse/JRASERVER-44801 says that the REST API call for deactivating users should be available in the next release (probably 8.2.2 or later). I suggest deferring till that is implemented.

Personally I'm going to investigate writing a custom REST endpoint [with ScriptRunner](https://www.adaptavist.com/doco/display/SFJ/Automatically+deactivate+inactive+JIRA+users).

**Comment by SLRover** [comment]
Hello everyone! Currently methods revoked in https://github.com/atlassian-api/atlassian-python-api/pull/229
We are waiting new feature in https://jira.atlassian.com/browse/JRASERVER-44801

**Comment by gonchik** [comment]
@SLRover  Please, wait. 
On my instance it works well :) Also, I have additional rest endpoint. 
Better way to set as deprecated

**Comment by SLRover** [comment]
@gonchik Are you mean ScriptRunner endpoint? On my both instances (Jira 7 and Jira 8) this method don't work too.

**Comment by SLRover** [comment]
Hey, @gonchik! I reverted commit which exclude user deactivate methods in https://github.com/atlassian-api/atlassian-python-api/pull/229 pull request.
I hope, we find solution for deactivating users in Jira. 👍

**Comment by gonchik** [comment]
as I see on 8.3.0 will be supported by design :)

**Comment by gonchik** [comment]
Hi @SLRover  ,
Let's deliver a new release and use the latest Jira version :)
