### ISSUE TITLE
Incorrect key in confluence.get_all_pages_from_space

### ISSUE THREAD

**Issue by timgc** [atlassian-api/atlassian-python-api#183]
https://github.com/atlassian-api/atlassian-python-api/blob/159fa246e71ca33fc5b019c508eed5d5cb9e45d4/atlassian/confluence.py#L184

`spaceKey` should be `SpaceKey`

Current method returns no pages.

**Comment by timgc** [comment]
https://github.com/atlassian-api/atlassian-python-api/blob/159fa246e71ca33fc5b019c508eed5d5cb9e45d4/atlassian/confluence.py#L100

as well

**Comment by gonchik** [comment]
Hi! 
On which version have you checked?
Also, doc shows the same view?
Because I double checked looks like everything is good,
https://docs.atlassian.com/ConfluenceServer/rest/6.15.2/#api/content-getContent
https://developer.atlassian.com/cloud/confluence/rest/#api-content-get

also, our daily scripts work well.

Cheers,
Gonchik Tsymzhitov

**Comment by gonchik** [comment]
Hi @timgc , 
Maybe did I check incorrectly? 

Cheers,
Gonchik Tsymzhitov

**Comment by gonchik** [comment]
close issue as can not reproduce it
