### ISSUE TITLE
atlassian.rest_client

### ISSUE THREAD

**Issue by wkihara** [atlassian-api/atlassian-python-api#196]
Hello, 

Just came across this python module and a basic setup, I tried to run confluence.create_page as documented and got this error.

No handlers could be found for logger "atlassian.rest_client"

Regards,
William

**Comment by gonchik** [comment]
Hi, 
could you provide the debug logs, please ? 
I would like to reproduce it on my side as well. 

Cheers,
Gonchik

**Comment by echoe** [comment]
I've run into this running a test, I believe it's because you need to specify the default logging in that specific test, something like:
import logging
logging.basicConfig()

That will clear up the issue.

You can see hints to this in parts of the examples, e.g. https://github.com/atlassian-api/atlassian-python-api/blob/master/examples/bitbucket-projects-administrators.py 
but it could definitely be clearer.

**Comment by gonchik** [comment]
Hi! 
I hope that workaround will help 
https://github.com/atlassian-api/atlassian-python-api/commit/ff0a9973809e0dcf8324fce5f1fe3541048cc4ac
