### ISSUE TITLE
Patch version breaks API

### ISSUE THREAD

**Issue by christian-harnisch-tallence** [atlassian-api/atlassian-python-api#302]
Upgrading from 1.13.15 to 1.13.24, calls to update_page with positional arguments are broken. The parameters were reordered: `parent_id` was moved towards the end.

With 1.13.15 the function signature was:
`def update_page(self, parent_id, page_id, title, body, type='page', representation='storage', minor_edit=False):`

With 1.13.24 (and probably earlier) it now is instead:
`def update_page(self, page_id, title, body, parent_id=None, type='page', representation='storage', minor_edit=False):`

The commit where the reordering happened was bfdb7194dae560449ca69196b05d4ede1f1dcce7

**Comment by gonchik** [comment]
Hi! 
Thanks for caught it

**Comment by gonchik** [comment]
Hi @christian-harnisch-tallence , 
Can we go forward based on that PR #304 >

**Comment by christian-harnisch-tallence** [comment]
Hi @gonchik!
Sure, thanks for taking this as opportunity to clean up the rest of the API. I adjusted my calls in the meantime.
A cleaned API isn't an issue, in fact I_welcome clean-ups. I'm more concerned with getting "warned" by a version increment. Basically, increments in the patch version (using vocabulary from [semantic versioning](https://semver.org/) here) tell me "don't worry, just upgrade and you'll be fine". At least that's a commonly used convention. May I ask, since you are on 1.13.27 (at the time of this writing), what's your versioning scheme?

**Comment by gonchik** [comment]
Hi @christian-harnisch-tallence !

About versioning, in reality I would like to follow the common versioning after 2.0.0 release. 
Because under 0.x and 1.x  I decided that as beta. Which you can follow that as beta badge. 
BTW, we can I am happy more and more users are using that library. 
Hence I will more and more see the API related. Also, I will write a short summary for the next bigger change. 
In your situation, I would say please, update into latest greatest version.:)

Cheers,
Gonchik Tsymzhitov
