### ISSUE TITLE
Bitbucket: API V2 update?

### ISSUE THREAD

**Issue by gclarke42** [atlassian-api/atlassian-python-api#540]
I am trying to write a script to parse some of out Bitbucket cloud pull request info and I am having some trouble using this API.  It seems like it is still using api 1 to interface which (I beleive?) is no longer supported.  Is there plans to update this api to use V2?

**Comment by gonchik** [comment]
Hi! 
Sorry for the delay, 
@gclarke42  please, have a look like this condition based on the self.cloud field of class. 
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/bitbucket.py#L32

That's should cover you request,
if you have a good idea, we are open to change :)

**Comment by j4b0l** [comment]
I can see that cloud part seems quite outdated, so I have to agree with @gclarke42 
As an example:
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/bitbucket.py#L569
for cloud solution uses:
`url = 'rest/api/2.0/projects/{projectKey}/repos'.format(projectKey=project_key)`
while in fact specified path returns 404, as now it looks like it should be more like:
`url = 'api/2.0/repositories/{workspace}?project.key={projectKey}'.format(projectKey=project_key, workspace=workspace)`

Morever here:
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/bitbucket.py#L2076
While pagination now operates on full URLs and response fields like 'next', 'prev' and 'page.
See https://developer.atlassian.com/bitbucket/api/2/reference/ for details on current API layout.

Is there any plan to have it updated soon?

**Comment by Spacetown** [comment]
I've started to rework the API calls to use private functions to create the url which uses as default the `api_root` and `api_version` given in constructor. This is not easy because some methods use a different values for both.

Also the paging isn't working for all API's as mentioned in #500. While working on the rework I thought to split the server and the cloud implementation because they use different URLs and paging methods.
My idea is to implement the BitBucket in an object oriented way and using iteratos. E.g. the function `get_projects(self)` returns a generator for instances of `BitBucket.Project`, the instance of a project can be used to access the project informations,... Ther will be no need for the limit and start arguments, if the end of a project page is reached, the next page is queried from the server.

**Comment by Spacetown** [comment]
@gclarke42 The pull request are implemented in the latest version.

**Comment by gonchik** [comment]
@Spacetown  Thank you for your work
