### ISSUE TITLE
Jira: Can't create Jira project

### ISSUE THREAD

**Issue by NamespaceNick** [atlassian-api/atlassian-python-api#553]
I cannot currently see any way to create a Jira project. Is this functionality supported?

**Comment by gonchik** [comment]
Hi @NicolasDWilliams , 
That functionality is not supported yet.
I will be happy to read your use case.

To understand how it will be easier to create methods

**Comment by gonchik** [comment]
is it ok to support only that api request?
https://docs.atlassian.com/software/jira/docs/api/REST/7.13.0/#api/2/project-createProject

After possible to wrap the next type of templates
https://confluence.atlassian.com/jirakb/creating-projects-via-rest-api-in-jira-963651978.html

**Comment by NicolasDWilliams** [comment]
> Hi @NicolasDWilliams ,
> That functionality is not supported yet.
> I will be happy to read your use case.
> 
> To understand how it will be easier to create methods
My organization works on game projects, and being able to have a script that just creates a new jira game project with all the correct configurations, permissions, board and sprints would be very useful.


> is it ok to support only that api request?
> https://docs.atlassian.com/software/jira/docs/api/REST/7.13.0/#api/2/project-createProject
> 
> After possible to wrap the next type of templates
> https://confluence.atlassian.com/jirakb/creating-projects-via-rest-api-in-jira-963651978.html

I think those requests would be good. However, I also discovered an API request that would help a lot with my specific use case, which makes use of the "Create with shared configuration" option when creating a Jira project. This is helpful because it avoids creating a bunch of redundant permission schemes, issue type schemes, etc. That are just going to quickly be switched to use our default / preferred schemes.

Here is the API endpoint: {JIRA_SERVER_URL}/rest/project-templates/1.0/createshared/{TEMPLATE_PROJ_ID}

Sorry if my issue / responses aren't properly formatted or best use case. I've been a programmer for about 5 years but this is actually the first GitHub issue I've ever created!

**Comment by gonchik** [comment]
Hi!

Thanks for your clarification. 
I just started to check project related methods, as short term solution added for now that one
https://github.com/atlassian-api/atlassian-python-api/blob/master/atlassian/jira.py#L1240
in the future I will add more wrapped parameters. 

Thanks for your request, I've started reorganize exist methods in jira.py, it was a previously a small wrapper. 
Now as I see in the lib covered a various methods, excluding project related one. Hence I will be happy to get from you a PR. 

Regarding Best practices, it's interesting to get from you some advice and helps :) 

Cheers,
Gonchik Tsymzhitov

**Comment by dephekt** [comment]
Hey @NamespaceNick,

The `rest/project-templates/1.0/createshared` endpoint is essentially undocumented as best I can tell. Some have reverse engineered the required payload by following the procedure in the web UI while having their browser developer console opened and then inspecting the POST request sent to the server.

I am happy to add support for that, however, as far as I can tell this endpoint is only supported in Jira Server and Jira Datacenter which I do not have access to -- my organization uses Jira Cloud. If this is supported in Jira Cloud, I can and will write support for that.

If you use Jira Server or Jira Datacenter with a commercial license, you can generate a free developer license and if I have that, I can setup a development Jira Server and test support for this. Let me know if you're interested in that.

**Comment by dephekt** [comment]
@NamespaceNick If you still need this functionality, I would appreciate your testing the method I created for this and let me know if it works or not and if there are any error messages: https://github.com/atlassian-api/atlassian-python-api/pull/730#issuecomment-785622883
