### ISSUE TITLE
[Bitbucket Cloud] Authentication keeps failing.

### ISSUE THREAD

**Issue by WriteCodeEveryday** [atlassian-api/atlassian-python-api#633]
I'm trying to authenticate for bitbucket.org using username@company.com.
I created an API Token and I am using it as a password.

`bitbucket = Bitbucket(
        url='https://api.bitbucket.org',
        username=os.getenv("BITBUCKET_USER"), password=os.getenv("BITBUCKET_PASSWORD"),
        cloud=True)

repo = bitbucket.get_repo('PROJECT', 'REPO')
`

This gets me a 
`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.bitbucket.org/2.0/projects/PROJECT/repos/REPO`

I'm a noob and I am totally fine being told that I have done a stupid but I can't seem to get the authorization to work.
I am willing to add documentation for bitbucket cloud if someone tells me how this is supposed to work.

**Comment by gonchik** [comment]
Hi @WriteCodeEveryday , 
Do you mean the token is correct and did not work ?
I am asking because it should works

**Comment by WriteCodeEveryday** [comment]
Yes, the token didn't work, even though it was correct.

I gave it repo access writes (read, write, admin)

**Comment by nborisenko** [comment]
Same issue.

**Comment by jensvog** [comment]
If you are using app passwords you have to use your username instead of your E-Mail. You can find your username under: Your profile and settings -> Account settings -> Bitbucket profile settings. [Source](https://stackoverflow.com/questions/39886995/how-to-access-bitbucket-using-app-password)

Some general infos for others, that are reading this:
* You can authenticate with your e-mail and password to the Bitbucket REST API. The Jira and Confluence REST API prevent that. There you always need an access token.
* You cannot use tokens from your general Atlassian account to authenticate to Bitbucket. You have to create "App passwords". They are under: Your profile and settings -> Account settings -> App passwords.
[Bitbucket REST API Authentification](https://developer.atlassian.com/bitbucket/api/2/reference/meta/authentication)

**Comment by jensvog** [comment]
I created a PR to update the documentation: https://github.com/atlassian-api/atlassian-python-api/pull/663. I hope with this it gets more clear, how you can login to Bitbucket.

**Comment by jensvog** [comment]
Hi @gonchik,
I think this issue can be closed. The error is because the thread starter used his E-Mail and an API Token (App password) for authentication. As mentioned, if you use an API Token (App password), you have to use your bitbucket username for log-in. That is a limitation from Bitbucket. It does not work with the E-Mail.

> If you are using app passwords you have to use your username instead of your E-Mail. You can find your username under: Your profile and settings -> Account settings -> Bitbucket profile settings. [Source](https://stackoverflow.com/questions/39886995/how-to-access-bitbucket-using-app-password)

This is now also stated in the documentation by the PR mentioned above.

**Comment by gonchik** [comment]
@jensvog thank you for your input and changes!
