### ISSUE TITLE
[Test] Adding coverage report

### ISSUE THREAD

**Issue by Spacetown** [atlassian-api/atlassian-python-api#657]
What about adding coverage report to the test?
New or changed endpoints should also be full covered by the test.

**Comment by gonchik** [comment]
Hi! 
It's sounds interesting. Let's start and then we can see the exactly what will it be

**Comment by Spacetown** [comment]
At the moment the GitHub actions are running with Python 3.4, 3.5, 3.6, 3,7, 3.8, 3.9 and the dev branch inside docker. All tests start tox which uses python 3.8.5.
Shall we use one docker container with e.g. 3.8 and run the test with tox for all python versions in parallel or shall we move the tests from tox to the makefile from which tox is started inside the docker container?

**Comment by gonchik** [comment]
Hm, that's interesting. 
Because correctly, one sandbox - one docker - 1 tests (tox) - 1 version. 
then do tests in parallel. 

As usual, the detailed situation with python 3.8.5, interesting to me. Because our code is not big difference across with minor python version. 
Based on that, at the moment it does not matter. 
What do you think ?

**Comment by Spacetown** [comment]
I think also that the code and the test don't depend on the minor version of python. Therefore in tox py3 shall be used and the docker image shall be created with different python versions. This is working now in #658. I'll close this issue and we can do further discussions in the PR.
