### ISSUE TITLE
Add link issue

### ISSUE THREAD

**Issue by sirio81** [atlassian-api/atlassian-python-api#724]
Hi, I can't find the syntax to add a "linked issue" to a task.
Looking at the browser console when adding a link I see the request payload:

  'issuelinks': [{"type": {"id": "10204"},"inwardIssue": {"key": "TST-9"}, "outwardIssue": {"key": "TST-7"}},]

Could you please explain how I can do that by jira api?

**Comment by dephekt** [comment]
This is more a question for the Atlassian community since you're talking about the REST API and generally Github issues shouldn't be used for support questions. That being said, you're looking for the `rest/api/2/issueLink` endpoint [described here](https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-links/#api-rest-api-2-issuelink-post).

I looked at the Python code for this package and that endpoint appears to be exposed by the `Jira.create_issue_link()` method [found here](https://github.com/atlassian-api/atlassian-python-api/blob/235af5ce5140472f67b28f32b5c07bad7302235a/atlassian/jira.py#L1985-L2011).

This method is specifically for adding internal (e.g. Jira issue to Jira issue) links, not for remote links. For those, you want the `Jira.create_or_update_issue_remote_links()` method. It's exposing the REST API `rest/api/2/issue/{issue_key}/remotelink` endpoint.
